---
title: "Vignette Title"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{far functions}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

This package was created for the Mastering Sofware Development in R Course week4 quiz.

The purpose of this assessment is for you to combine your skills of creating,
writing, documenting, and testing an R package with releasing that package on
GitHub. In this assessment you'll be taking the R files from Week 2's assessment
about documentation and putting that file in an R package.
For this assessment you must

1. write a vignette to include in your package using knitr and R Markdown

2. write at least one test written using testthat

3. put your package on GitHub

4. set up the repository so that the package can be checked and built on Travis
less 
􀂎
5. Once your package has built on Travis and the build is passing with no errors,
warnings, or notes you should add your Travis badge to the README.md file of
your package repository.

## Results

The assignment was completed including a successful Travis integration build 







